version: "3"

services:
  app1:
    build: .
    ports:
      - "8000:8000"
  app2:
    build: .
    ports:
      - "8001:8000"
  app3:
    build: .
    ports:
      - "8002:8000"
  app4:
    build: .
    ports:
      - "8003:8000"
  app5:
    build: .
    ports:
      - "8004:8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
      - app3
      - app4
      - app5
