version: "3"

services:
  app1:
    build: .
    container_name: app1
    expose:
      - "8000"

  app2:
    build: .
    container_name: app2
    expose:
      - "8000"

  app3:
    build: .
    container_name: app3
    expose:
      - "8000"

  app4:
    build: .
    container_name: app4
    expose:
      - "8000"

  app5:
    build: .
    container_name: app5
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3
      - app4
      - app5
